apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-middle
  namespace: mesh-benchmark
  labels: { app: service-middle }
spec:
  replicas: 1
  selector:
    matchLabels: { app: service-middle }
  template:
    metadata:
      labels: { app: service-middle }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        sidecar.istio.io/proxyCPU: "50m"
        sidecar.istio.io/proxyCPULimit: "500m"
        sidecar.istio.io/proxyMemory: "64Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
        config.linkerd.io/proxy-cpu-request: "50m"
        config.linkerd.io/proxy-cpu-limit: "500m"
        config.linkerd.io/proxy-memory-request: "64Mi"
        config.linkerd.io/proxy-memory-limit: "128Mi"
    spec:
      containers:
        - name: service-middle
          image: service-mesh/service-middle:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: benchmark-common-config
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 1000m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: service-middle
  namespace: mesh-benchmark
spec:
  selector: { app: service-middle }
  ports:
    - name: http
      port: 8080
      targetPort: 8080